### ISSUE TITLE
Issue with longranger basic - docopts and mrp

### ISSUE THREAD

**Issue by jpenalba** [adreau/ReMIX#1]
Hi, 

I've started trying out the pipeline but have been running into issues when it runs the modified version of longranger. The initial longranger basic command it has locating 'docopts' and 'mrp'. Are these executable supposed to be included in the modified longranger package? I also tried adding the path to these executables in the unmodified longranger-2.2.2 but then hit errors locating the 'docopt' module. Thank you.

Josh Penalba

**Comment by ellieearmstrong** [comment]
Hi! I am also having the same issue. I piped it to the normal long ranger for the majority of the pipeline, but one I got to the step which requires longranger-remix (ReporterMol), it errors. 

Would love some advice. :)

**Comment by adreau** [comment]
Hi! 
Longranger-remix repository contains only the files related to Long Ranger (equivalent to  'longranger-[version]/longranger-cs/[version]' folder). It order to run it, you will need also the software dependencies that are  bundled in the Long Ranger package (eg, anaconda-cs for 'docopts' and 'mrp'). 
I have added the complete list of steps for installing longranger-remix in the README file. Please let me know if you encounter any problems!

**Comment by ellieearmstrong** [comment]
Hi there!

Thanks for the clarification and sorry to bother you again.

I incorporated the changes. Basically whenever I run longranger-remix I just get shown the options

`Longranger` reporterMol (2.1.3)
Copyright (c) 2017 10x Genomics, Inc.  All rights reserved.
-------------------------------------------------------------------------------

Usage:
    longranger mkfastq
    longranger demux

    longranger wgs
    longranger targeted

    longranger align
    longranger basic

    longranger mkvcf
    longranger mkref

    longranger testrun
    longranger upload
    longranger sitecheck

    longranger `reporterMol`


Nothing else will appear (I've tried help, running the commands in the script, etc.). This also prints as just the output file if I run the whole command (the error file is empty).

Maybe I am missing something else?

Thank you again for your time and help!!!

**Comment by adreau** [comment]
I forgot to indicate the link to the longranger-remix binaries. Could you please add the following lines at the very end of the 'longranger-[version]/sourceme.bash' file:

# longranger-remix
export MROPATH="$DIR/longranger-cs/longranger-remix/mro:$DIR/longranger-cs/longranger-remix/tenkit/mro:$MROPATH"
export PATH="$DIR/longranger-cs/longranger-remix/bin:$PATH"

**Comment by jpenalba** [comment]
Thanks for this! This seemed to have worked and has gone through the next steps. I did have to change line 50 `--fastqs=${path}` to `--fastqs=${path}/${testName}` as the previous lines created the symbolic link within the new folder named by `$testName`.
